-- Dummy Data Insert Script

-- Users
INSERT INTO users (name, email, password_hash, role) VALUES ('Admin User', 'admin@finpilot.ai', 'dummy_hash', 'manager');

-- Customers
INSERT INTO customers (name, email, phone) VALUES ('Sneha Chopra', 'sneha.chopra67@example.com', '+919389053541');
INSERT INTO customers (name, email, phone) VALUES ('Prakash Bhatia', 'prakash.bhatia79@example.com', '+919133685214');
INSERT INTO customers (name, email, phone) VALUES ('Kavya Patel', 'kavya.patel4@example.com', '+919427251578');
INSERT INTO customers (name, email, phone) VALUES ('Riya Verma', 'riya.verma42@example.com', '+919406758863');
INSERT INTO customers (name, email, phone) VALUES ('Pooja Pillai', 'pooja.pillai3@example.com', '+919856205591');
INSERT INTO customers (name, email, phone) VALUES ('Ananya Yadav', 'ananya.yadav47@example.com', '+919047315296');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Das', 'arjun.das60@example.com', '+919257163105');
INSERT INTO customers (name, email, phone) VALUES ('Prakash Rao', 'prakash.rao63@example.com', '+919093465751');
INSERT INTO customers (name, email, phone) VALUES ('Vijay Bose', 'vijay.bose29@example.com', '+919104889318');
INSERT INTO customers (name, email, phone) VALUES ('Kavya Joshi', 'kavya.joshi99@example.com', '+919864731857');
INSERT INTO customers (name, email, phone) VALUES ('Simran Sethi', 'simran.sethi28@example.com', '+919111746479');
INSERT INTO customers (name, email, phone) VALUES ('Aarav Pillai', 'aarav.pillai2@example.com', '+919711294881');
INSERT INTO customers (name, email, phone) VALUES ('Siddharth Tiwari', 'siddharth.tiwari47@example.com', '+919249452192');
INSERT INTO customers (name, email, phone) VALUES ('Suresh Chauhan', 'suresh.chauhan32@example.com', '+919477973088');
INSERT INTO customers (name, email, phone) VALUES ('Rohan Sharma', 'rohan.sharma56@example.com', '+919187453283');
INSERT INTO customers (name, email, phone) VALUES ('Kriti Das', 'kriti.das93@example.com', '+919433623357');
INSERT INTO customers (name, email, phone) VALUES ('Riya Saha', 'riya.saha33@example.com', '+919694929662');
INSERT INTO customers (name, email, phone) VALUES ('Kriti Banerjee', 'kriti.banerjee87@example.com', '+919767432329');
INSERT INTO customers (name, email, phone) VALUES ('Riya Patel', 'riya.patel87@example.com', '+919267002675');
INSERT INTO customers (name, email, phone) VALUES ('Gaurav Nair', 'gaurav.nair3@example.com', '+919349595709');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Pillai', 'arjun.pillai41@example.com', '+919095499629');
INSERT INTO customers (name, email, phone) VALUES ('Neha Ahuja', 'neha.ahuja66@example.com', '+919339797131');
INSERT INTO customers (name, email, phone) VALUES ('Priya Thakur', 'priya.thakur20@example.com', '+919792080000');
INSERT INTO customers (name, email, phone) VALUES ('Kavya Bose', 'kavya.bose38@example.com', '+919825416278');
INSERT INTO customers (name, email, phone) VALUES ('Anil Gupta', 'anil.gupta4@example.com', '+919479285905');
INSERT INTO customers (name, email, phone) VALUES ('Ramesh Chauhan', 'ramesh.chauhan8@example.com', '+919194032788');
INSERT INTO customers (name, email, phone) VALUES ('Nitin Chauhan', 'nitin.chauhan35@example.com', '+919026813230');
INSERT INTO customers (name, email, phone) VALUES ('Vikram Sethi', 'vikram.sethi39@example.com', '+919710984160');
INSERT INTO customers (name, email, phone) VALUES ('Neha Sen', 'neha.sen81@example.com', '+919810941851');
INSERT INTO customers (name, email, phone) VALUES ('Harish Dubey', 'harish.dubey22@example.com', '+919360805683');
INSERT INTO customers (name, email, phone) VALUES ('Saurabh Mishra', 'saurabh.mishra52@example.com', '+919756381355');
INSERT INTO customers (name, email, phone) VALUES ('Rajat Gupta', 'rajat.gupta57@example.com', '+919386773377');
INSERT INTO customers (name, email, phone) VALUES ('Sunil Chauhan', 'sunil.chauhan19@example.com', '+919547387023');
INSERT INTO customers (name, email, phone) VALUES ('Ananya Joshi', 'ananya.joshi13@example.com', '+919440339517');
INSERT INTO customers (name, email, phone) VALUES ('Alok Dutta', 'alok.dutta34@example.com', '+919601733583');
INSERT INTO customers (name, email, phone) VALUES ('Vikram Malhotra', 'vikram.malhotra45@example.com', '+919111419686');
INSERT INTO customers (name, email, phone) VALUES ('Ishita Khatri', 'ishita.khatri55@example.com', '+919394045781');
INSERT INTO customers (name, email, phone) VALUES ('Kriti Mishra', 'kriti.mishra44@example.com', '+919683505259');
INSERT INTO customers (name, email, phone) VALUES ('Raj Reddy', 'raj.reddy54@example.com', '+919667779596');
INSERT INTO customers (name, email, phone) VALUES ('Aditya Sethi', 'aditya.sethi1@example.com', '+919657452669');
INSERT INTO customers (name, email, phone) VALUES ('Simran Dasgupta', 'simran.dasgupta13@example.com', '+919876234272');
INSERT INTO customers (name, email, phone) VALUES ('Ashish Singh', 'ashish.singh25@example.com', '+919605939921');
INSERT INTO customers (name, email, phone) VALUES ('Rohan Khanna', 'rohan.khanna52@example.com', '+919814153305');
INSERT INTO customers (name, email, phone) VALUES ('Ajay Kapoor', 'ajay.kapoor32@example.com', '+919894181246');
INSERT INTO customers (name, email, phone) VALUES ('Shruti Kaur', 'shruti.kaur48@example.com', '+919878508584');
INSERT INTO customers (name, email, phone) VALUES ('Saurabh Yadav', 'saurabh.yadav36@example.com', '+919605914593');
INSERT INTO customers (name, email, phone) VALUES ('Ashish Saha', 'ashish.saha75@example.com', '+919827541574');
INSERT INTO customers (name, email, phone) VALUES ('Karan Mishra', 'karan.mishra59@example.com', '+919844522749');
INSERT INTO customers (name, email, phone) VALUES ('Saurabh Saha', 'saurabh.saha83@example.com', '+919643463184');
INSERT INTO customers (name, email, phone) VALUES ('Harish Mishra', 'harish.mishra95@example.com', '+919153897153');
INSERT INTO customers (name, email, phone) VALUES ('Ishita Saha', 'ishita.saha7@example.com', '+919236437848');
INSERT INTO customers (name, email, phone) VALUES ('Manish Chopra', 'manish.chopra57@example.com', '+919322156641');
INSERT INTO customers (name, email, phone) VALUES ('Anil Pillai', 'anil.pillai78@example.com', '+919570238729');
INSERT INTO customers (name, email, phone) VALUES ('Sanjay Dubey', 'sanjay.dubey3@example.com', '+919358316705');
INSERT INTO customers (name, email, phone) VALUES ('Ajay Banerjee', 'ajay.banerjee83@example.com', '+919094718528');
INSERT INTO customers (name, email, phone) VALUES ('Amit Bhasin', 'amit.bhasin32@example.com', '+919047275358');
INSERT INTO customers (name, email, phone) VALUES ('Amit Menon', 'amit.menon55@example.com', '+919095980446');
INSERT INTO customers (name, email, phone) VALUES ('Kartik Rao', 'kartik.rao27@example.com', '+919692345803');
INSERT INTO customers (name, email, phone) VALUES ('Karan Bose', 'karan.bose56@example.com', '+919435938488');
INSERT INTO customers (name, email, phone) VALUES ('Tanvi Dutta', 'tanvi.dutta44@example.com', '+919477992771');
INSERT INTO customers (name, email, phone) VALUES ('Rajesh Oberoi', 'rajesh.oberoi41@example.com', '+919428847198');
INSERT INTO customers (name, email, phone) VALUES ('Harish Bose', 'harish.bose14@example.com', '+919525934711');
INSERT INTO customers (name, email, phone) VALUES ('Harish Kaur', 'harish.kaur95@example.com', '+919595220566');
INSERT INTO customers (name, email, phone) VALUES ('Ramesh Khanna', 'ramesh.khanna81@example.com', '+919247267498');
INSERT INTO customers (name, email, phone) VALUES ('Prakash Saha', 'prakash.saha16@example.com', '+919331666966');
INSERT INTO customers (name, email, phone) VALUES ('Amit Sengupta', 'amit.sengupta44@example.com', '+919043712522');
INSERT INTO customers (name, email, phone) VALUES ('Tanvi Pandey', 'tanvi.pandey31@example.com', '+919216434364');
INSERT INTO customers (name, email, phone) VALUES ('Anil Chopra', 'anil.chopra33@example.com', '+919124874671');
INSERT INTO customers (name, email, phone) VALUES ('Alok Chopra', 'alok.chopra80@example.com', '+919531455841');
INSERT INTO customers (name, email, phone) VALUES ('Suresh Dubey', 'suresh.dubey38@example.com', '+919719200767');
INSERT INTO customers (name, email, phone) VALUES ('Rajat Das', 'rajat.das25@example.com', '+919159122893');
INSERT INTO customers (name, email, phone) VALUES ('Raj Tiwari', 'raj.tiwari6@example.com', '+919806723367');
INSERT INTO customers (name, email, phone) VALUES ('Anil Khanna', 'anil.khanna95@example.com', '+919739387796');
INSERT INTO customers (name, email, phone) VALUES ('Kriti Reddy', 'kriti.reddy97@example.com', '+919617877157');
INSERT INTO customers (name, email, phone) VALUES ('Shruti Khanna', 'shruti.khanna31@example.com', '+919205441745');
INSERT INTO customers (name, email, phone) VALUES ('Shruti Reddy', 'shruti.reddy44@example.com', '+919858561023');
INSERT INTO customers (name, email, phone) VALUES ('Aditya Kapoor', 'aditya.kapoor29@example.com', '+919693790641');
INSERT INTO customers (name, email, phone) VALUES ('Raj Sharma', 'raj.sharma39@example.com', '+919318939216');
INSERT INTO customers (name, email, phone) VALUES ('Prakash Sharma', 'prakash.sharma30@example.com', '+919356757987');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Pandey', 'arjun.pandey70@example.com', '+919077199850');
INSERT INTO customers (name, email, phone) VALUES ('Tanvi Khatri', 'tanvi.khatri53@example.com', '+919480127870');
INSERT INTO customers (name, email, phone) VALUES ('Ashish Oberoi', 'ashish.oberoi25@example.com', '+919456469518');
INSERT INTO customers (name, email, phone) VALUES ('Nitin Mukherjee', 'nitin.mukherjee98@example.com', '+919457985901');
INSERT INTO customers (name, email, phone) VALUES ('Pooja Bhatia', 'pooja.bhatia96@example.com', '+919457270821');
INSERT INTO customers (name, email, phone) VALUES ('Rahul Narang', 'rahul.narang32@example.com', '+919644310314');
INSERT INTO customers (name, email, phone) VALUES ('Sneha Reddy', 'sneha.reddy35@example.com', '+919232364561');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Chauhan', 'arjun.chauhan31@example.com', '+919214769538');
INSERT INTO customers (name, email, phone) VALUES ('Ishita Mishra', 'ishita.mishra88@example.com', '+919478381561');
INSERT INTO customers (name, email, phone) VALUES ('Gaurav Singh', 'gaurav.singh44@example.com', '+919267410950');
INSERT INTO customers (name, email, phone) VALUES ('Rajat Rajput', 'rajat.rajput92@example.com', '+919050056099');
INSERT INTO customers (name, email, phone) VALUES ('Aarav Chauhan', 'aarav.chauhan28@example.com', '+919078338567');
INSERT INTO customers (name, email, phone) VALUES ('Tanvi Kumar', 'tanvi.kumar15@example.com', '+919192980863');
INSERT INTO customers (name, email, phone) VALUES ('Manish Pandey', 'manish.pandey77@example.com', '+919289504512');
INSERT INTO customers (name, email, phone) VALUES ('Riya Grover', 'riya.grover51@example.com', '+919263947884');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Rao', 'arjun.rao8@example.com', '+919098620240');
INSERT INTO customers (name, email, phone) VALUES ('Anil Sen', 'anil.sen69@example.com', '+919839192847');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Thakur', 'arjun.thakur19@example.com', '+919895276227');
INSERT INTO customers (name, email, phone) VALUES ('Mukesh Khatri', 'mukesh.khatri68@example.com', '+919885043536');
INSERT INTO customers (name, email, phone) VALUES ('Kartik Gupta', 'kartik.gupta21@example.com', '+919501145569');
INSERT INTO customers (name, email, phone) VALUES ('Rajat Sharma', 'rajat.sharma37@example.com', '+919338587871');
INSERT INTO customers (name, email, phone) VALUES ('Kunal Patel', 'kunal.patel35@example.com', '+919695068608');
INSERT INTO customers (name, email, phone) VALUES ('Rajat Tiwari', 'rajat.tiwari85@example.com', '+919880125142');
INSERT INTO customers (name, email, phone) VALUES ('Kriti Malhotra', 'kriti.malhotra68@example.com', '+919084283295');
INSERT INTO customers (name, email, phone) VALUES ('Deepak Tiwari', 'deepak.tiwari52@example.com', '+919541227083');
INSERT INTO customers (name, email, phone) VALUES ('Karan Malhotra', 'karan.malhotra24@example.com', '+919214906804');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Ahuja', 'arjun.ahuja56@example.com', '+919027346801');
INSERT INTO customers (name, email, phone) VALUES ('Nitin Sethi', 'nitin.sethi88@example.com', '+919411726012');
INSERT INTO customers (name, email, phone) VALUES ('Ananya Ghosh', 'ananya.ghosh66@example.com', '+919774845446');
INSERT INTO customers (name, email, phone) VALUES ('Dhruv Banerjee', 'dhruv.banerjee8@example.com', '+919585310839');
INSERT INTO customers (name, email, phone) VALUES ('Anjali Rao', 'anjali.rao18@example.com', '+919800757751');
INSERT INTO customers (name, email, phone) VALUES ('Kunal Kapoor', 'kunal.kapoor98@example.com', '+919588223856');
INSERT INTO customers (name, email, phone) VALUES ('Vihaan Dasgupta', 'vihaan.dasgupta98@example.com', '+919570388695');
INSERT INTO customers (name, email, phone) VALUES ('Rishi Tiwari', 'rishi.tiwari25@example.com', '+919431971682');
INSERT INTO customers (name, email, phone) VALUES ('Ashish Menon', 'ashish.menon9@example.com', '+919006412134');
INSERT INTO customers (name, email, phone) VALUES ('Siddharth Grover', 'siddharth.grover83@example.com', '+919165055415');
INSERT INTO customers (name, email, phone) VALUES ('Kartik Yadav', 'kartik.yadav38@example.com', '+919367453853');
INSERT INTO customers (name, email, phone) VALUES ('Suresh Verma', 'suresh.verma98@example.com', '+919795624782');
INSERT INTO customers (name, email, phone) VALUES ('Rajesh Pandey', 'rajesh.pandey38@example.com', '+919418588109');
INSERT INTO customers (name, email, phone) VALUES ('Nitin Grover', 'nitin.grover33@example.com', '+919010216121');
INSERT INTO customers (name, email, phone) VALUES ('Kunal Sengupta', 'kunal.sengupta96@example.com', '+919460893573');
INSERT INTO customers (name, email, phone) VALUES ('Sanjay Kaur', 'sanjay.kaur97@example.com', '+919390892812');
INSERT INTO customers (name, email, phone) VALUES ('Rahul Pandey', 'rahul.pandey15@example.com', '+919276819958');
INSERT INTO customers (name, email, phone) VALUES ('Priya Patel', 'priya.patel53@example.com', '+919540810404');
INSERT INTO customers (name, email, phone) VALUES ('Mukesh Chauhan', 'mukesh.chauhan39@example.com', '+919587383428');
INSERT INTO customers (name, email, phone) VALUES ('Rahul Kumar', 'rahul.kumar76@example.com', '+919151816600');
INSERT INTO customers (name, email, phone) VALUES ('Siddharth Ghosh', 'siddharth.ghosh60@example.com', '+919311510350');
INSERT INTO customers (name, email, phone) VALUES ('Sunil Reddy', 'sunil.reddy26@example.com', '+919342733147');
INSERT INTO customers (name, email, phone) VALUES ('Yash Sengupta', 'yash.sengupta64@example.com', '+919011276304');
INSERT INTO customers (name, email, phone) VALUES ('Mukesh Khanna', 'mukesh.khanna79@example.com', '+919748009419');
INSERT INTO customers (name, email, phone) VALUES ('Sunil Sengupta', 'sunil.sengupta94@example.com', '+919711463229');
INSERT INTO customers (name, email, phone) VALUES ('Anjali Gupta', 'anjali.gupta28@example.com', '+919435155148');
INSERT INTO customers (name, email, phone) VALUES ('Kavya Nair', 'kavya.nair50@example.com', '+919649960048');
INSERT INTO customers (name, email, phone) VALUES ('Aditya Bose', 'aditya.bose62@example.com', '+919819645181');
INSERT INTO customers (name, email, phone) VALUES ('Siddharth Mukherjee', 'siddharth.mukherjee11@example.com', '+919279926677');
INSERT INTO customers (name, email, phone) VALUES ('Vikram Sengupta', 'vikram.sengupta37@example.com', '+919323606511');
INSERT INTO customers (name, email, phone) VALUES ('Sneha Narang', 'sneha.narang29@example.com', '+919036509704');
INSERT INTO customers (name, email, phone) VALUES ('Prakash Verma', 'prakash.verma16@example.com', '+919787959173');
INSERT INTO customers (name, email, phone) VALUES ('Suresh Nair', 'suresh.nair69@example.com', '+919404816379');
INSERT INTO customers (name, email, phone) VALUES ('Ananya Thakur', 'ananya.thakur87@example.com', '+919708036489');
INSERT INTO customers (name, email, phone) VALUES ('Kriti Thakur', 'kriti.thakur15@example.com', '+919773226593');
INSERT INTO customers (name, email, phone) VALUES ('Rohan Mishra', 'rohan.mishra98@example.com', '+919728313186');
INSERT INTO customers (name, email, phone) VALUES ('Prakash Menon', 'prakash.menon32@example.com', '+919469242449');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Banerjee', 'arjun.banerjee1@example.com', '+919214926773');
INSERT INTO customers (name, email, phone) VALUES ('Sanjay Reddy', 'sanjay.reddy64@example.com', '+919223830731');
INSERT INTO customers (name, email, phone) VALUES ('Gaurav Verma', 'gaurav.verma77@example.com', '+919805199802');
INSERT INTO customers (name, email, phone) VALUES ('Vihaan Menon', 'vihaan.menon5@example.com', '+919244894337');
INSERT INTO customers (name, email, phone) VALUES ('Rohan Yadav', 'rohan.yadav81@example.com', '+919665371209');
INSERT INTO customers (name, email, phone) VALUES ('Simran Menon', 'simran.menon52@example.com', '+919851169074');
INSERT INTO customers (name, email, phone) VALUES ('Vihaan Ghosh', 'vihaan.ghosh90@example.com', '+919138475177');
INSERT INTO customers (name, email, phone) VALUES ('Prakash Chopra', 'prakash.chopra83@example.com', '+919555826281');
INSERT INTO customers (name, email, phone) VALUES ('Rajesh Sengupta', 'rajesh.sengupta41@example.com', '+919112052812');
INSERT INTO customers (name, email, phone) VALUES ('Saurabh Sethi', 'saurabh.sethi94@example.com', '+919895687873');
INSERT INTO customers (name, email, phone) VALUES ('Rajat Pillai', 'rajat.pillai86@example.com', '+919123692214');
INSERT INTO customers (name, email, phone) VALUES ('Kriti Verma', 'kriti.verma79@example.com', '+919611254435');
INSERT INTO customers (name, email, phone) VALUES ('Ashish Dubey', 'ashish.dubey4@example.com', '+919624009927');
INSERT INTO customers (name, email, phone) VALUES ('Harish Narang', 'harish.narang6@example.com', '+919794505433');
INSERT INTO customers (name, email, phone) VALUES ('Deepak Grover', 'deepak.grover45@example.com', '+919676189862');
INSERT INTO customers (name, email, phone) VALUES ('Amit Pillai', 'amit.pillai98@example.com', '+919420462258');
INSERT INTO customers (name, email, phone) VALUES ('Priya Sengupta', 'priya.sengupta25@example.com', '+919798840236');
INSERT INTO customers (name, email, phone) VALUES ('Riya Kaur', 'riya.kaur94@example.com', '+919590736658');
INSERT INTO customers (name, email, phone) VALUES ('Tanvi Yadav', 'tanvi.yadav53@example.com', '+919232461839');
INSERT INTO customers (name, email, phone) VALUES ('Kavya Iyer', 'kavya.iyer89@example.com', '+919842568895');
INSERT INTO customers (name, email, phone) VALUES ('Yash Bhasin', 'yash.bhasin18@example.com', '+919004001292');
INSERT INTO customers (name, email, phone) VALUES ('Deepak Menon', 'deepak.menon61@example.com', '+919780940524');
INSERT INTO customers (name, email, phone) VALUES ('Ramesh Sen', 'ramesh.sen83@example.com', '+919600594194');
INSERT INTO customers (name, email, phone) VALUES ('Pooja Malhotra', 'pooja.malhotra36@example.com', '+919791855699');
INSERT INTO customers (name, email, phone) VALUES ('Pooja Bose', 'pooja.bose89@example.com', '+919089549958');
INSERT INTO customers (name, email, phone) VALUES ('Arjun Khatri', 'arjun.khatri97@example.com', '+919040961614');
INSERT INTO customers (name, email, phone) VALUES ('Rahul Reddy', 'rahul.reddy50@example.com', '+919782925510');
INSERT INTO customers (name, email, phone) VALUES ('Dhruv Sengupta', 'dhruv.sengupta48@example.com', '+919560627198');
INSERT INTO customers (name, email, phone) VALUES ('Neha Verma', 'neha.verma10@example.com', '+919459475388');
INSERT INTO customers (name, email, phone) VALUES ('Kunal Tiwari', 'kunal.tiwari97@example.com', '+919389772721');
INSERT INTO customers (name, email, phone) VALUES ('Ananya Mukherjee', 'ananya.mukherjee41@example.com', '+919891664013');
INSERT INTO customers (name, email, phone) VALUES ('Diya Khanna', 'diya.khanna29@example.com', '+919450954779');
INSERT INTO customers (name, email, phone) VALUES ('Mukesh Bose', 'mukesh.bose82@example.com', '+919399223652');
INSERT INTO customers (name, email, phone) VALUES ('Pranav Rao', 'pranav.rao31@example.com', '+919467559213');
INSERT INTO customers (name, email, phone) VALUES ('Ajay Joshi', 'ajay.joshi2@example.com', '+919289806872');
INSERT INTO customers (name, email, phone) VALUES ('Riya Tiwari', 'riya.tiwari79@example.com', '+919659452107');
INSERT INTO customers (name, email, phone) VALUES ('Pooja Mishra', 'pooja.mishra5@example.com', '+919360705918');
INSERT INTO customers (name, email, phone) VALUES ('Karan Joshi', 'karan.joshi38@example.com', '+919417797875');
INSERT INTO customers (name, email, phone) VALUES ('Raj Nair', 'raj.nair42@example.com', '+919582444879');
INSERT INTO customers (name, email, phone) VALUES ('Pooja Nair', 'pooja.nair47@example.com', '+919874197701');
INSERT INTO customers (name, email, phone) VALUES ('Deepak Bhatia', 'deepak.bhatia45@example.com', '+919226592995');
INSERT INTO customers (name, email, phone) VALUES ('Tanvi Pillai', 'tanvi.pillai45@example.com', '+919137084492');
INSERT INTO customers (name, email, phone) VALUES ('Rishi Bose', 'rishi.bose28@example.com', '+919572982368');
INSERT INTO customers (name, email, phone) VALUES ('Aditya Mishra', 'aditya.mishra62@example.com', '+919705328698');
INSERT INTO customers (name, email, phone) VALUES ('Anjali Joshi', 'anjali.joshi25@example.com', '+919824473404');
INSERT INTO customers (name, email, phone) VALUES ('Ishita Kapoor', 'ishita.kapoor28@example.com', '+919415568786');
INSERT INTO customers (name, email, phone) VALUES ('Manish Grover', 'manish.grover5@example.com', '+919358976244');
INSERT INTO customers (name, email, phone) VALUES ('Ananya Verma', 'ananya.verma26@example.com', '+919006839219');
INSERT INTO customers (name, email, phone) VALUES ('Ishita Sengupta', 'ishita.sengupta9@example.com', '+919249689445');
INSERT INTO customers (name, email, phone) VALUES ('Sanjay Chauhan', 'sanjay.chauhan44@example.com', '+919779082039');
INSERT INTO customers (name, email, phone) VALUES ('Aarav Patel', 'aarav.patel30@example.com', '+919837433448');
INSERT INTO customers (name, email, phone) VALUES ('Anil Saha', 'anil.saha24@example.com', '+919793592390');
INSERT INTO customers (name, email, phone) VALUES ('Manish Sengupta', 'manish.sengupta28@example.com', '+919210753887');
INSERT INTO customers (name, email, phone) VALUES ('Sneha Patel', 'sneha.patel57@example.com', '+919688132783');
INSERT INTO customers (name, email, phone) VALUES ('Ashish Bhasin', 'ashish.bhasin35@example.com', '+919720448243');
INSERT INTO customers (name, email, phone) VALUES ('Rajat Menon', 'rajat.menon33@example.com', '+919745496209');
INSERT INTO customers (name, email, phone) VALUES ('Sunil Nair', 'sunil.nair36@example.com', '+919719031386');
INSERT INTO customers (name, email, phone) VALUES ('Karan Singh', 'karan.singh99@example.com', '+919285964076');

-- Transactions
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (154, 4102.37, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (84, 2165.08, 'Failed', 'PayPal', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (59, 1121.92, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (60, 3831.21, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (68, 2551.44, 'Pending', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (43, 4963.09, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (181, 2471.69, 'Pending', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (67, 4365.58, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (173, 1769.84, 'Failed', 'Credit Card', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (99, 3526.83, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (83, 2948.81, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (107, 1431.46, 'Failed', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (133, 1056.30, 'Failed', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (83, 4273.36, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (33, 1621.12, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (187, 810.94, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (23, 202.97, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (142, 1474.72, 'Failed', 'Bank Transfer', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (188, 2027.77, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (102, 3923.58, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (78, 105.47, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (183, 1983.85, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (105, 667.67, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (132, 3662.30, 'Failed', 'Debit Card', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (180, 300.80, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (127, 3884.14, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (136, 3796.72, 'Failed', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (17, 4039.28, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (71, 2087.64, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (67, 1709.33, 'Failed', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (63, 1042.78, 'Failed', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (14, 4989.47, 'Pending', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (177, 854.90, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (178, 1583.93, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (193, 2992.18, 'Failed', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (195, 4907.33, 'Failed', 'PayPal', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (81, 224.82, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (16, 408.24, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (137, 1970.99, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (74, 4237.84, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (177, 4297.24, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (200, 736.39, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (175, 2760.92, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (139, 1941.96, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (174, 1101.14, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (15, 1502.35, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (102, 215.07, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (194, 4100.69, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (145, 672.55, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (168, 1457.42, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (85, 4529.16, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (23, 2633.43, 'Failed', 'Credit Card', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (164, 2369.25, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (57, 3067.35, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (8, 1524.48, 'Failed', 'UPI', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (30, 2973.79, 'Failed', 'Bank Transfer', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (41, 2308.43, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (117, 118.31, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (40, 4586.55, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (149, 2208.81, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (7, 3813.37, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (53, 4595.34, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (71, 1708.14, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (178, 1839.48, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (140, 393.29, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (52, 4441.71, 'Failed', 'Credit Card', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (140, 2536.36, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (35, 1554.91, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (100, 4918.93, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (134, 882.39, 'Failed', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (87, 3980.30, 'Failed', 'Bank Transfer', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (31, 1715.04, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (27, 1690.28, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (9, 4122.55, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (73, 2181.71, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (18, 1279.30, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (99, 1242.80, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (56, 3059.62, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (182, 1065.87, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (191, 1240.91, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (9, 4418.42, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (195, 4395.48, 'Failed', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (44, 4671.11, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (152, 3070.84, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (199, 119.49, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (55, 458.75, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (9, 4402.36, 'Failed', 'Credit Card', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (64, 1155.85, 'Failed', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (84, 1344.34, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (171, 1500.62, 'Failed', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (59, 1899.84, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (96, 3000.02, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (93, 4147.80, 'Failed', 'UPI', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (97, 1025.93, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (65, 2152.54, 'Failed', 'Bank Transfer', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (160, 4972.26, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (172, 4158.83, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (38, 733.66, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (93, 3010.58, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (145, 3411.97, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (128, 458.61, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (19, 1157.86, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (25, 437.49, 'Pending', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (112, 4338.84, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (35, 125.28, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (50, 365.49, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (51, 4274.76, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (69, 4194.42, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (94, 2677.55, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (124, 1718.75, 'Failed', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (29, 3587.88, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (170, 1508.63, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (119, 107.76, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (3, 787.61, 'Failed', 'Bank Transfer', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (23, 1364.41, 'Pending', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (180, 421.04, 'Failed', 'Credit Card', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (43, 4152.52, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (17, 1568.65, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (86, 4807.06, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (84, 3812.08, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (75, 139.58, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (33, 1304.17, 'Failed', 'PayPal', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (175, 4065.30, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (156, 4678.66, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (147, 180.12, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (6, 1446.62, 'Failed', 'Bank Transfer', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (59, 4478.29, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (135, 484.36, 'Failed', 'UPI', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (93, 4843.11, 'Failed', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (20, 2295.32, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (186, 3710.45, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (43, 1035.02, 'Failed', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (89, 23.30, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (105, 236.52, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (18, 271.21, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (7, 3970.80, 'Failed', 'Debit Card', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (53, 1983.35, 'Failed', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (198, 997.46, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (29, 3862.30, 'Failed', 'UPI', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (196, 4686.00, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (23, 2917.60, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (22, 4098.50, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (169, 72.08, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (35, 811.75, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (122, 4103.09, 'Pending', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (80, 3956.97, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (44, 1201.91, 'Suspicious', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (48, 2618.87, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (64, 2016.06, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (44, 2901.35, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (80, 21.05, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (23, 3007.68, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (70, 2408.60, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (119, 3472.29, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (146, 3117.16, 'Failed', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (134, 2327.42, 'Failed', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (146, 1858.36, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (66, 880.15, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (32, 4058.80, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (52, 2537.46, 'Success', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (11, 403.06, 'Failed', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (9, 677.37, 'Failed', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (31, 1739.26, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (107, 1019.77, 'Failed', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (198, 3370.04, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (152, 277.70, 'Suspicious', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (182, 667.20, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (89, 1186.83, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (97, 3514.36, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (154, 2966.18, 'Pending', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (62, 1562.87, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (99, 920.24, 'Failed', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (144, 3544.80, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (98, 2703.49, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (11, 1447.57, 'Suspicious', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (10, 1294.17, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (63, 2781.42, 'Failed', 'Debit Card', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (97, 2624.26, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (191, 1424.17, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (144, 296.54, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (143, 442.09, 'Pending', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (153, 4357.56, 'Failed', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (199, 644.08, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (123, 3518.54, 'Pending', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (167, 519.77, 'Failed', 'Bank Transfer', 'Refunded');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (157, 546.25, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (15, 3837.89, 'Success', 'Bank Transfer', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (80, 2633.44, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (145, 877.32, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (72, 4975.82, 'Success', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (111, 773.23, 'Success', 'UPI', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (17, 2479.08, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (7, 1765.65, 'Failed', 'Debit Card', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (137, 937.58, 'Suspicious', 'PayPal', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (30, 3181.26, 'Suspicious', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (188, 237.86, 'Failed', 'Credit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (188, 1909.06, 'Success', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (132, 2007.94, 'Pending', 'Debit Card', 'none');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (103, 2075.71, 'Failed', 'Credit Card', 'Pending');
INSERT INTO transactions (customer_id, amount, status, payment_method, refund_status) VALUES (93, 1396.04, 'Suspicious', 'PayPal', 'none');

-- Tickets
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (106, 11, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (41, 183, 'I did not authorize this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (135, 62, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (54, 47, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (181, 105, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (31, 67, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (180, 45, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (39, 53, 'I did not authorize this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (190, 58, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (161, 133, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (126, 97, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (96, 132, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (147, 176, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (186, 105, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (147, 138, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (90, 95, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (17, 34, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (81, 4, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (26, 23, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (182, 116, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (59, 200, 'I did not authorize this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (109, 45, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (33, 112, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (38, 183, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (192, 24, 'I did not authorize this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (30, 154, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (88, 159, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (37, 196, 'I did not authorize this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (54, 40, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (99, 25, 'I did not authorize this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (154, 2, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (18, 65, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (149, 69, 'I did not authorize this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (9, 72, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (148, 112, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (6, 59, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (171, 122, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (124, 157, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (27, 106, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (94, 73, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (155, 198, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (78, 194, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (160, 106, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (110, 135, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (16, 25, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (106, 31, 'I was overcharged for this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (78, 22, 'The merchant did not receive my payment.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (174, 175, 'I want to cancel and refund this transaction.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (159, 97, 'My payment failed but money was deducted.');
INSERT INTO tickets (customer_id, transaction_id, issue_text) VALUES (120, 69, 'I want to cancel and refund this transaction.');

-- Fraud Cases
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (187, 98, 'Suspicious IP address');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (155, 96, 'Large transaction size anomaly');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (107, 79, 'Suspicious IP address');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (7, 88, 'Large transaction size anomaly');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (8, 79, 'Large transaction size anomaly');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (168, 91, 'Multiple login locations');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (162, 94, 'Device changed recently');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (183, 90, 'Suspicious IP address');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (143, 85, 'Large transaction size anomaly');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (180, 93, 'Suspicious IP address');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (186, 96, 'Large transaction size anomaly');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (10, 88, 'Suspicious IP address');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (26, 85, 'Device changed recently');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (59, 87, 'Large transaction size anomaly');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (135, 93, 'Card velocity too high');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (179, 80, 'Large transaction size anomaly');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (69, 91, 'Suspicious IP address');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (186, 97, 'Card velocity too high');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (161, 95, 'Card velocity too high');
INSERT INTO fraud_cases (transaction_id, risk_score, reason) VALUES (65, 94, 'Card velocity too high');



-- Audit Logs Dummy Data
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Verified', 'Auto-raised ticket for failed payment', 96.3, '2026-08-07 18:18:53.817');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Categorized Ticket', 'Auto-categorized issue as High priority based on keyword analysis', 99.0, '2026-08-07 22:54:58.291');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Refund Approved', 'Resolved customer inquiry autonomously', 98.7, '2026-08-08 00:44:46.986');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Verified', 'Escalated to human agent due to low confidence', 91.3, '2026-08-07 22:06:22.627');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Categorized Ticket', 'Automated refund for duplicate charge detected within 1m timeframe', 90.8, '2026-08-07 13:55:15.811');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Transaction Frozen', 'Escalated to human agent due to low confidence', 89.1, '2026-08-07 06:57:20.548');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Created Ticket', 'Transaction is legitimate and user authorized the payment', 95.9, '2026-08-07 17:45:24.837');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Verified', 'Suspicious login attempt from unknown IP pattern', 91.1, '2026-08-07 18:37:51.483');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Verified', 'Flagged due to unusual device location', 93.4, '2026-08-07 05:05:07.168');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Categorized Ticket', 'Resolved customer inquiry autonomously', 88.3, '2026-08-07 20:04:01.034');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Categorized Ticket', 'Transaction is legitimate and user authorized the payment', 97.3, '2026-08-07 23:46:11.143');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Transaction Frozen', 'Suspicious login attempt from unknown IP pattern', 90.7, '2026-08-07 04:36:56.927');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Transaction Frozen', 'Auto-raised ticket for failed payment', 97.2, '2026-08-07 12:38:59.256');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Created Ticket', 'Automated refund for duplicate charge detected within 1m timeframe', 94.1, '2026-08-08 01:04:26.354');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Refund Approved', 'Suspicious login attempt from unknown IP pattern', 98.2, '2026-08-07 07:12:24.107');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Refund Approved', 'Resolved customer inquiry autonomously', 87.4, '2026-08-07 11:04:08.495');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Categorized Ticket', 'Transaction is legitimate and user authorized the payment', 85.7, '2026-08-07 05:46:10.638');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Refund Approved', 'Automated refund for duplicate charge detected within 1m timeframe', 96.5, '2026-08-07 06:06:22.030');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Verified', 'Auto-categorized issue as High priority based on keyword analysis', 93.3, '2026-08-07 06:22:44.481');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Refund Approved', 'Auto-categorized issue as High priority based on keyword analysis', 99.0, '2026-08-07 22:56:58.612');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Refund Approved', 'Auto-categorized issue as High priority based on keyword analysis', 93.7, '2026-08-07 16:34:07.734');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Verified', 'Flagged due to unusual device location', 88.0, '2026-08-08 01:36:39.483');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Verified', 'Resolved customer inquiry autonomously', 96.0, '2026-08-07 12:22:24.054');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Created Ticket', 'Flagged due to unusual device location', 90.0, '2026-08-07 07:54:59.152');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Transaction Frozen', 'Automated refund for duplicate charge detected within 1m timeframe', 86.6, '2026-08-08 03:04:36.487');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Verified', 'Suspicious login attempt from unknown IP pattern', 94.4, '2026-08-07 18:27:42.171');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Verified', 'Auto-raised ticket for failed payment', 90.1, '2026-08-08 02:14:14.952');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Created Ticket', 'Auto-raised ticket for failed payment', 97.1, '2026-08-07 11:03:59.681');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Verified', 'Suspicious login attempt from unknown IP pattern', 90.8, '2026-08-07 22:42:06.801');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Created Ticket', 'Auto-categorized issue as High priority based on keyword analysis', 87.9, '2026-08-07 10:29:03.217');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Created Ticket', 'Escalated to human agent due to low confidence', 96.5, '2026-08-07 13:02:09.698');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Verified', 'Escalated to human agent due to low confidence', 98.2, '2026-08-07 05:37:24.258');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Created Ticket', 'Resolved customer inquiry autonomously', 98.8, '2026-08-07 17:42:20.361');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Created Ticket', 'Auto-raised ticket for failed payment', 89.9, '2026-08-07 09:01:04.070');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Refund Approved', 'Escalated to human agent due to low confidence', 94.4, '2026-08-07 04:48:20.570');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Created Ticket', 'Auto-categorized issue as High priority based on keyword analysis', 91.1, '2026-08-07 18:54:55.634');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Refund Approved', 'Resolved customer inquiry autonomously', 93.5, '2026-08-07 13:44:57.995');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Categorized Ticket', 'Transaction is legitimate and user authorized the payment', 94.7, '2026-08-07 14:34:49.014');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Transaction Frozen', 'Flagged due to unusual device location', 85.5, '2026-08-07 23:31:29.171');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Refund Approved', 'Resolved customer inquiry autonomously', 90.6, '2026-08-07 21:55:05.524');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Verified', 'Flagged due to unusual device location', 94.4, '2026-08-07 10:43:27.544');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Transaction Frozen', 'Escalated to human agent due to low confidence', 98.6, '2026-08-07 06:42:11.533');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Transaction Frozen', 'Resolved customer inquiry autonomously', 89.6, '2026-08-07 20:35:57.300');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Verified', 'Escalated to human agent due to low confidence', 96.6, '2026-08-07 23:13:29.006');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Refund Approved', 'Flagged due to unusual device location', 85.6, '2026-08-07 22:04:09.989');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Created Ticket', 'Flagged due to unusual device location', 88.6, '2026-08-07 13:44:18.472');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Fraud Agent', 'Categorized Ticket', 'Resolved customer inquiry autonomously', 99.8, '2026-08-07 05:18:01.909');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Created Ticket', 'Automated refund for duplicate charge detected within 1m timeframe', 91.7, '2026-08-08 02:46:50.335');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('FinPilot AI Core', 'Verified', 'Resolved customer inquiry autonomously', 93.6, '2026-08-08 00:47:07.696');
INSERT INTO audit_logs (agent, action, reason, confidence, created_at) VALUES ('Payment Agent', 'Verified', 'Flagged due to unusual device location', 96.4, '2026-08-07 09:17:17.577');
